### ISSUE TITLE
Cuda version sensible defaults

### ISSUE THREAD

**Issue by egull** [Green-Phys/green-gpu#3]
Replace the current GPU compilation code with the one from Nvidia:

https://github.com/NVIDIA/TensorRT/blob/main/CMakeLists.txt

so we don't have hardcoded versions. See here:

https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#gpu-feature-list

for versions and capabilities. See also here:
https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/

**Comment by iskakoff** [comment]
fixed in 9e137ff900ab0953bd2996601bb978e180662778
